/* conflict_table.h - GENERATED by tools/gen_conflict.py, do not edit. */
#ifndef CONFLICT_TABLE_H
#define CONFLICT_TABLE_H

#define AVIMS_NUM_MOVEMENTS 12

/* movement id = approach*3 + intent ; approaches N,E,S,W ; intents R,S,L */
static const char *avims_move_name[AVIMS_NUM_MOVEMENTS] = { "NR", "NS", "NL", "ER", "ES", "EL", "SR", "SS", "SL", "WR", "WS", "WL" };

/* conflict[a][b] == 1  ->  movements a and b may NOT cross simultaneously */
static const unsigned char avims_conflict[AVIMS_NUM_MOVEMENTS][AVIMS_NUM_MOVEMENTS] = {
    {0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0},
    {1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1},
    {1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1},
    {0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1},
    {1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1},
    {0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0},
    {0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0},
    {0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1},
    {1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1},
    {0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1},
    {0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1},
    {0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0},
};

static inline int avims_conflict_pair(int a, int b) {
    return (int) avims_conflict[a][b];
}

#endif /* CONFLICT_TABLE_H */
